"""initial tables

Revision ID: 82dc906b0145
Revises: 
Create Date: 2026-03-12 16:59:54.364929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82dc906b0145'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('class_level', sa.String(length=20), nullable=True),
    sa.Column('combination', sa.String(length=50), nullable=True),
    sa.Column('is_class_teacher', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('student_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('dorm_items', sa.Text(), nullable=True),
    sa.Column('term', sa.String(length=20), nullable=True),
    sa.Column('school_fees', sa.Integer(), nullable=True),
    sa.Column('other_contributions', sa.Text(), nullable=True),
    sa.Column('character_assessment', sa.Text(), nullable=True),
    sa.Column('health_state', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('student_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('class_level', sa.String(length=20), nullable=False),
    sa.Column('test1', sa.Float(), nullable=True),
    sa.Column('test2', sa.Float(), nullable=True),
    sa.Column('exam_type', sa.String(length=50), nullable=True),
    sa.Column('exam_marks', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('average', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(length=5), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subject_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('class_level', sa.String(length=50), nullable=False),
    sa.Column('subjects', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher_subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('class_level', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_subject')
    op.drop_table('subject_assignment')
    op.drop_table('student_result')
    op.drop_table('student_profiles')
    op.drop_table('user')
    # ### end Alembic commands ###
