"""Add exam_month and exam_year to StudentResult

Revision ID: b3bbd420d5ee
Revises: 228db277fe88
Create Date: 2026-03-13 19:48:18.079007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3bbd420d5ee'
down_revision = '228db277fe88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exam_month', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('exam_year', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_result', schema=None) as batch_op:
        batch_op.drop_column('exam_year')
        batch_op.drop_column('exam_month')

    # ### end Alembic commands ###
